# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('species', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('climate', models.CharField(max_length=40)),
                ('diameter', models.PositiveIntegerField()),
                ('population', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='photos',
            field=models.ManyToManyField(to='characters.Photo'),
        ),
        migrations.AddField(
            model_name='character',
            name='planet',
            field=models.ManyToManyField(to='characters.Planet'),
        ),
    ]
