# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photos',
            field=models.ManyToManyField(blank='True', to='characters.Photo'),
        ),
        migrations.AlterField(
            model_name='character',
            name='planet',
            field=models.ManyToManyField(blank='True', to='characters.Planet'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank='True', max_length=40),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.PositiveIntegerField(blank='True'),
        ),
    ]
